# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "avada forth app"
client_id = "35b5cf20e09900829cbd48f07fc61f68"
application_url = "https://mid-intensive-qty-configuring.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mid-intensive-qty-configuring.trycloudflare.com/auth/shopify/callback",
  "https://mid-intensive-qty-configuring.trycloudflare.com/authSa/shopify/callback",
  "https://mid-intensive-qty-configuring.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "newavadastore.myshopify.com"
